#!/usr/bin/env bash
#
# Homebrew maintainence script responsible
# for keeping package manager and package
# up to date and perform regular cleanup

brew update
brew outdated
brew upgrade
brew doctor
brew cleanup

if [ "$1" = "--cask" ]; then
 brew cu --cleanup -a -f -y 
fi
