#!/usr/bin/env bash

#
# @author Ali
# git-config
#
# description: configure git settings
#
# options:
#
# -l: use local mode to change user name and email for working git repository
#

echo "What is your name?"
read name
echo "What is your e-mail?"
read email

if [[ $1 = "-l" ]]; then
    echo "Local Mode"
    git config user.name $name
    git config user.email $email
else
    touch ~/.gitignore
    git config --global user.name $name
    git config --global user.email $email
    git config --global color.ui auto
    git config --global core.autocrlf input
    git config --global core.editor "vim"
    git config --global pull.rebase true
    git config --global push.default simple
    git config --global core.excludesfile ~/.gitignore
fi
